export const ActionTypes = {
  FETCH_PRODUCTS:'FETCH_PRODUCTS',
  LOADING:'LOADING',
  ADD_NEW_PRODUCT:'ADD_NEW_PRODUCT',
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  DELETE_TAB:'DELETE_TAB',
};
